version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: my_webserver
    ports:
    - "8088:80"
    volumes:
    - ./src:/var/www/html
    - ./docker/conf/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  mysql:
    image: mysql:5.7
    container_name: my_database
    restart: unless-stopped
    tty: true
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: search_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: mysql
  php:
    build:
      context: .
      dockerfile: docker/PHP.DockerFile
    container_name: my_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
  artisan:
    build:
      context: .
      dockerfile: docker/PHP.DockerFile
    container_name: my_artisan
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php','/var/www/html/artisan']